# Based upon:
#   https://github.com/actions/starter-workflows/blob/main/ci/go.yml

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:

    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.13, 1.14, 1.15, 1.16]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download Packages
        run: go get -t -v ./ably/...

      - name: Vet
        run: go vet ./ably/... ./scripts/...

      - name: Ensure generated code is up-to-date
        run: go generate ./... && [ -z "$(git status --porcelain)" ]

      - name: Test with JSON Protocol
        run: scripts/test.sh --protocol application/json

      # We explicitly do this clean between test runs in preference to specifying the slightly opaque `-count=1`
      # argument to subsequent test run executions.
      - name: Clean Test Cache
        run: go clean -testcache

      - name: Test with MessagePack Protocol
        run: scripts/test.sh --protocol application/x-msgpack
